name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: dependencies
      run: sudo apt install libtool docbook2x libboost-all-dev libcurl4-openssl-dev libxml2-dev libcppunit-dev
    - name: autoreconf
      run: autoreconf --install
    - name: autoconf
      run: autoconf
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
